homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='landing page'),
    path('add_status/', views.add_status, name='add_status')
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
import datetime

class Status(models.Model):
    status = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add =True)

homepage/forms.py
from django import forms
from .models import Status
from django.forms import ModelForm

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['status']
        labels = {'status':'Status',}
        widgets = {'status' : forms.Textarea(attrs={'class': 'form-control','type' : 'text', 'rows' : '3'}),}

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StatusForm
from .models import Status


# Create your views here.
def index(request):
    data = Status.objects.all()
    form = StatusForm()
    context = {'form' : form, 'data' : data}
    return render(request, 'landing page.html',context)
    
def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
    return redirect('/')

homepage/templates/landing page.html
{% load static from staticfiles%}


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>{% block title %}{% endblock %}</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>




  </head>
  <body style="background-color: #9be3de;">
    <!--content-->
    <div id="header" style="display: block; text-align: left; margin-left : 15%">
      <h2 style="color: black;">HALO, APA KABAR?</h2>
    </div>
    <div class="form-container" style="padding:2% 15% 2%; color: black">
      <form method="POST" action="{% url 'homepage:add_status' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="name">{{ form.status.label_tag }}</label>
            <div class="col-sm-10">
              {{ form.status }}
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-10" style="margin-top: 3%; padding: 1%;">
              <button type="submit" class="btn btn-primary" id="submit">Submit</button>
            </div>
          </div>
        </form>
        {% for db in data %}
               <small>{{ db.date }}</small>
               <p>{{ db.status }}</p>
               <hr></hr>
        {% endfor %}
    </div>
  </body>
</html>